---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calcom
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      calcom:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: calcom-secret
        containers:
          app:
            image:
              repository: calcom/cal.com
              tag: v5.0.19
            env:
              TZ: "Europe/Warsaw"
              NEXT_PUBLIC_WEBAPP_URL: 'https://book.exelent.click'
              NEXT_PUBLIC_API_V2_URL: 'http://localhost:5555/api/v2'
              NEXT_PUBLIC_LICENSE_CONSENT: 'agree'
              CALCOM_TELEMETRY_DISABLED: '0'
            envFrom: *envFrom
#            probes:
#              liveness: &probes
#                enabled: true
#                custom: true
#                spec:
#                  httpGet:
#                    path: /health
#                    port: &port 3000
#                  initialDelaySeconds: 0
#                  periodSeconds: 10
#                  timeoutSeconds: 1
#                  failureThreshold: 3
#              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: [ "ALL" ] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 3000
    route:
      app:
        hostnames: [ "book.exelent.click" ]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
