---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbit-helper
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbit-helper-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          # This is an example configuration file that documents all the options.
          # It will need to be modified for your specific use case.
          # Please refer to the link below for more details on how to set up the configuration file

          commands:
            # Dry run. Don't delete anything
            dry: false
            # Removes .torrent files from completed directory, that no more exist in the client of not
            # part of a specified categories
            monitor_completed: true

          qbittorrent:
            host: "qbittorrent.default.svc.cluster.local:8080"
            user: {{ .qbittorrent_username }}
            password: {{ .qbittorrent_password }}
            disable_ssl: true


          monitor_completed:
            # directory to monitor
            completed_dir: /data/torrents/.torrents/completed
            # will remove files if they are not part of a category
            categories:
              - tv
              - movies
  dataFrom:
    - extract:
        key: qbittorrent
      rewrite:
        - regexp:
            source: "(.*)"
            target: "qbittorrent_$1"
