---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${APP}-crunchy-postgres"
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        CLOUDFLARE_ACCOUNT_ID: "{{ .CLOUDFLARE_ACCOUNT_TAG }}"
        s3.conf: |
          [global]
          repo1-s3-key={{ .MINIO_POSTGRESS_ACCESS_KEY }}
          repo1-s3-key-secret={{ .MINIO_POSTGRESS_SECRET_KEY }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: crunchy-pgo
    - extract:
        key: minio
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${APP}-pguser-${APP}"
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      metadata:
        labels:
          postgres-operator.crunchydata.com/cluster: ${APP}
          postgres-operator.crunchydata.com/pguser: ${APP}
      data:
        password: "{{ .${APP}_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: ${APP}
