---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gluetun-secret
    template:
      engineVersion: v2
      data:
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        GLUETUN_CONTROL_SERVER_API_KEY: "{{ .GLUETUN_CONTROL_API_KEY }}"
        config.toml: |
          [[roles]]
          name = "qbittorrent"
          routes = ["GET /v1/portforward", "GET /v1/publicip/ip", "GET /v1/vpn/status", "PUT /v1/vpn/status"]
          auth = "apikey"
          apikey = "{{ .GLUETUN_CONTROL_API_KEY }}"
  dataFrom:
    - extract:
        key: qbittorrent
