apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
stringData:
    UI_USERNAME: ENC[AES256_GCM,data:ixqwojY=,iv:FTnXHfYa2xLdGRmsLE+tueRwgVqVoxeimlejGI0i0GU=,tag:vXMk3Bb+2vVC/WSetSX54g==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:+F84UWfEpMsEbnUj,iv:smkjjtylJbSBPn6LFZCw3b6n0RR8sTQvJoR1NsqzEnE=,tag:epsA/eENFqOwgsiuP1Wi8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuejlMZjdOVGk3U0V0aDgw
            MVBVR29COXY1RjEwL2U2dDVhdW5odk1Ma2lnClJjNFYxbVJPSndrVGRjV1orb2xZ
            Z3FkM0dYZWs0ZEZaUXMzLzZwVVcrV00KLS0tIDNnNFk3andkczJoWkdtejRZak95
            NlNhTStCdXhkQnVRNkV0ZzI4eTYzc00KW+HAq1Masonr84DsUaXreNR3V1+Q9K4T
            E+MosghU+4f40EKu69sSvzVzDk2+Gbhtgg1dVMUt5pP4bSfA8OdMRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-02T15:23:26Z"
    mac: ENC[AES256_GCM,data:xvdzguPf1Ne6jcbBr4S3keoSS3jmUtsGxKqocHLRXAI1THt3mW9RzNpRQhegte9+Px8tGyqTCvi0oGNBwHeVJ4RxaKK0zDRuxR7+8MQxF36iZjq8zi4IJg/5ONvk9rVzvjCHHxvQlaTSBILyT7n/U3KkrP1Hef21+R0yUJB3Gwo=,iv:L1nzWiAxq0hhFGmr3ImmT3++6b/7bc8XvzgiMFSYnU0=,tag:VlRdHVXjQbVj3H5r5LtmFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
