# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
stringData:
    #ENC[AES256_GCM,data:NJAvxg==,iv:nUuiTpCer9VfdH9XEAazPEOBZG+GER237A6J7g94GL4=,tag:CE4RlZsA7ZpMrIOcbobPgg==,type:comment]
    PROWLARR__API_KEY: ENC[AES256_GCM,data:JG5sExMvpRufLyizFV4v31Ax0vuzoJezXDNhdQ2MMc8=,iv:pPAC+7Uu30QQwQjamCBPJ1l0ekyg0QFJvBLFApnS+ic=,tag:ZH69V/Kh4cF21mpp+RitIw==,type:str]
    PROWLARR__POSTGRES_HOST: ENC[AES256_GCM,data:UT+IjdAI6amU/4XoLgQkQO+uag08fqqmewUs7vy7tdytUBYNYBfXZWyhmnJmRA==,iv:8nSYRQvSNH88Ta4h0QGjh8zJ3qotgUf5QQdKccTRwtY=,tag:n49gsZlWxspuODNGZtTS9Q==,type:str]
    PROWLARR__POSTGRES_PORT: ENC[AES256_GCM,data:hzTbSQ==,iv:Od5gpx3ftsdckw7k3tti4HWuxqffhs2viSSzU4TneXY=,tag:UG/+cR5BF6PWR6AEP7SWnw==,type:str]
    PROWLARR__POSTGRES_USER: ENC[AES256_GCM,data:2CCrm08munc=,iv:mmPn57h6UwXqftk8e7Zof6NvXaRMPpnimRttu8WCSsw=,tag:5wbFsESB9GTot5kOm8sE+A==,type:str]
    PROWLARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:icRir0O45u097WUTD3N9dg==,iv:mJ4SU/N3jsUr+MTRkEwo/gMSdfAed4i2Q986MAseXhI=,tag:8ahve66XFyyFKKdTQ8YXLQ==,type:str]
    PROWLARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:Fqx+6tO5dt0d2CbEnQ==,iv:jQoYZA+PYWg/R5ZBAH/XCQbD9jID45BbkHagqt+4oWw=,tag:uNXJVBrqNecBEbTqSIOLhw==,type:str]
    PROWLARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:yv+4vHp2iDjJsAsl,iv:NP927kxP2BJNrAyFIBYYImQhnluv3YeFgNwmpwh3PNs=,tag:hq/tr1CNtc0A5QGHI2RHTA==,type:str]
    #ENC[AES256_GCM,data:C+3f6GMq4+pzO8rN+hg=,iv:1Hc+2SW5gSBpQW/JMoGXPqd0iVZe6rmRMmG22OMuSBo=,tag:MInfTZhT8eUJoiwG0uCcag==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:N1vXXbheeMAE7sL/nb2EnK/e/Qw0ZMljuuE=,iv:ugKBWpi+o3Vi40Abp+Ha5viAx69DUc5i3+GjsrV7cmQ=,tag:3nxCM6RkgAd9XmR/gMwULw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4g9CoZMdoNNbvzG3CgR1aOH3jqVEFF7n70PPK3IJt3TLzv9U2EzgJI3dipCROQ==,iv:xX/B7fxAnzcolp/r8IyrmoHZQX27zizsXxcqtn7mC2s=,tag:lqh4zJlatwm7U9za34q7oA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:3uesxoKl5V0=,iv:zb8gfpDR8/nuk99HI7LGOMttUpCZG4n5yX1U+6n1vGM=,tag:6he1OS+/iHVAQ4acSmMMzw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Cu2htpQgCZ/bw1g3B8XELw==,iv:N5YdLUnUp6mcGdOM4iL5qgp0pcNdvHskVrcjWP9nQ4Y=,tag:dacYVoEB1THgN0SWMhPizQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UzZmNjk5dy81Zk94bzF1
            OGZIWlV1YTUwWG52ZDZsUHViQjBIb0ZMVFdFCmk3RjgxQmtEa084WklOMVpVcTNw
            QUYza1N1RFh5T2pZS1NiQkZleEpsSEEKLS0tIElSRHZ2WmZXR1RLTW5VSmZOdWZT
            WFpqY3pDdk1FTkN1VVVjNUsrZGNhM2sKvyoVPJw6FfbOSuz0urnt0GlrNnPMYgXR
            d1I/06kCeeCGeQNyb77qK+cIGg8oJCDlXXzPhkIBFSGXnEFtL5g8Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T18:28:18Z"
    mac: ENC[AES256_GCM,data:hoZKXOSK7GzrZo2zUpVBWqIL2ZTjtB6owCX+c6xsKDHXvGl5a97HzZfbGKk6kpMa9v4V99c+OKDqtkG5lh/YFSWnirUT0wUxxhjSh6rXZi2oaiWMCFg64O2xD/UNBgGOobYpk+rDCldz+X8iCNhkA3o6Swh5IpXZV9+vqMfwifQ=,iv:nSMQ2U3GahG/G6/HBuqXEBX9qrqdachCSu0MVWhTejM=,tag:2ij21vc0p4AWo0kQWztycw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
