---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: portainer
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: portainer.png
    gethomepage.dev/name: Portainer
    gethomepage.dev/group: "Monitoring & Observability"
    gethomepage.dev/description: Container management UI
    gethomepage.dev/weight: "3"
    gethomepage.dev/widget.type: portainer
    gethomepage.dev/widget.url: http://portainer.observability.svc.cluster.local:9000
    gethomepage.dev/widget.env: "2"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PORTAINER_TOKEN}}"
spec:
  hostnames: ["portainer.exelent.click"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: portainer
          namespace: observability
          port: 9000
