---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            group_by: ["alertname", "job"]
            group_interval: 10m
            group_wait: 1m
            receiver: discord
            repeat_interval: 12h
            routes:
              - receiver: "null"
                matchers:
                  - alertname =~ "InfoInhibitor"
              - receiver: discord
                continue: true
                matchers:
                  - severity = "critical"
          inhibit_rules:
            - equal: ["alertname", "namespace"]
              source_matchers:
                - severity = "critical"
              target_matchers:
                - severity = "warning"
          receivers:
            - name: "null"
            - name: discord
              discord_configs:
                - webhook_url: "{{ .ALERTMANAGER_DISCORD_WEBHOOK }}"
                  send_resolved: true
  dataFrom:
    - extract:
        key: discord
