---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        ALERTMANAGER_HEARTBEAT_URL: "{{ .ALERTMANAGER_HEARTBEAT_WEBHOOK }}"
        ALERTMANAGER_DISCORD_URL: "{{ .ALERTMANAGER_DISCORD_WEBHOOK }}"
  dataFrom:
    - extract:
        key: discord
    - extract:
        key: healthchecks
