---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent-tools-manage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: default
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "0 * * * *"
          timeZone: "${TIMEZONE}"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          main:
            image:
              repository: ghcr.io/stuffanthings/qbit_manage
              tag: latest@sha256:00995edba6e57dcc986d16138daf9468f7c26477a60b49b90b874bb7f234713f
            env:
              QBT_RUN: "true"
              QBT_CONFIG: "/config/config.yaml"
            args:
              - --config
              - /app/config.yaml
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 256M
        pod:
          restartPolicy: OnFailure
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      config-file:
        type: secret
        name: qbit-manage-secret
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
      downloads:
        type: nfs
        server: "${NAS_URL}"
        path: "${NAS_PATH}"
        globalMounts:
          - path: /data
