---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent-tools-manage
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: default
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "0 * * * *"
          timeZone: "Europe/Warsaw"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          main:
            image:
              repository: ghcr.io/stuffanthings/qbit_manage
              tag: latest@sha256:47bea77dcbe30a9deb1af5a21ebbd35443f49b68efdbaad4afe7b9b63a81dfd9
            env:
              QBT_RUN: "true"
              QBT_CONFIG: "/config/config.yaml"
            args:
              - --config
              - /app/config.yaml
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 256M
        pod:
          restartPolicy: OnFailure
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      config-file:
        type: secret
        name: qbit-manage-secret
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
      downloads:
        type: nfs
        server: "192.168.20.5"
        path: "/volume1/kubernetes"
        globalMounts:
          - path: /data
