---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent-tools-manage
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: default
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "0 * * * *"
          timeZone: "Europe/Warsaw"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        initContainers:
          copy-config-secret:
            image:
              repository: docker.io/library/alpine
              tag: 3.22.0
            command:
              - "sh"
              - "-c"
              - |
                mkdir -p /config &&
                cp -f /temp-dir/config.yaml /config/config.yaml &&
                ls -al /config
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
        containers:
          main:
            image:
              repository: ghcr.io/stuffanthings/qbit_manage
              tag: v4.5.3
            env:
              QBT_RUN: "true"
              QBT_CONFIG: "/config/config.yaml"
#            args:
#              - --config-file
#              - /app/config.yaml
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 256M
        pod:
          restartPolicy: OnFailure
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      downloads:
        type: nfs
        server: "192.168.20.5"
        path: "/volume1/kubernetes"
        globalMounts:
          - path: /data
      # Workaround to overcome that k8s secrets are always readOnly. Mount secret to a emptyDir, then copy it with init
      # container to the required path
      config-tmp:
        type: emptyDir
        globalMounts:
          - path: /temp-dir
      config:
        type: emptyDir
        globalMounts:
          - path: /config
      config-file:
        type: secret
        name: qbit-manage-secret
        globalMounts:
          - path: /temp-dir/config.yaml
            subPath: config.yaml
            readOnly: false
