---
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "README.md"
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: bootstrap/**/*
area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/*
area/taskfile:
  - changed-files:
      - any-glob-to-any-file: .taskfiles/**/*
      - any-glob-to-any-file: Taskfile*
area/renovate:
  - changed-files:
      - any-glob-to-any-file:
          - ".renovate/**/*"
          - ".renovaterc.json5"
area/scripts:
  - changed-files:
      - any-glob-to-any-file: "scripts/**/*"
area/talos:
  - changed-files:
      - any-glob-to-any-file: "talos/**/*"
