---
apiVersion: v1
kind: Service
metadata:
  name: minio-external-service
spec:
  type: ExternalName
  externalName: "${NAS_URL}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: "minio.png"
    gethomepage.dev/name: Minio
    gethomepage.dev/group: Storage
    gethomepage.dev/description: S3 compatible object storage
spec:
  ingressClassName: internal
  rules:
    - host: &host "minio.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-external-service
                port:
                  number: 9090
  tls:
    - hosts:
        - *host
