---
apiVersion: v1
kind: Service
metadata:
  name: pihole-external-service
spec:
  type: ExternalName
  externalName: "${RPI_URL}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: pi-hole.png
    gethomepage.dev/name: PiHole
    gethomepage.dev/group: Network
    gethomepage.dev/description: Network-wide Ad Blocking DNS
    gethomepage.dev/widget.type: pihole
    gethomepage.dev/widget.url: "http://${RPI_URL}"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PI_HOLE_TOKEN}}"
spec:
  rules:
    - host: "pihole.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pihole-external-service
                port:
                  number: 80
