---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-external-service
spec:
  type: ExternalName
  externalName: 192.168.0.41
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox-ingress
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: proxmox.png
    gethomepage.dev/name: Proxmox
    gethomepage.dev/group: hardware
    gethomepage.dev/description: Virtual Environment
    gethomepage.dev/widget.type: proxmox
    gethomepage.dev/widget.url: https://192.168.0.41:8006
    gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
    gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"
    gethomepage.dev/node: proxmox1
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
spec:
  ingressClassName: internal
  rules:
    - host: "proxmox.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxmox-external-service
                port:
                  number: 8006
