---
apiVersion: v1
kind: Service
metadata:
  name: sprut-external-service
spec:
  type: ExternalName
  externalName: "${RPI_URL}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spruthub-ingress
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: "https://sprut.${SECRET_DOMAIN}/favicon.ico"
    gethomepage.dev/name: Spruthub
    gethomepage.dev/group: Home
    gethomepage.dev/description: Zigbee hub and Homekit integration
spec:
  ingressClassName: internal
  rules:
    - host: &host "sprut.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sprut-external-service
                port:
                  number: 7777
