---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: democratic-csi
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.15.0
  url: oci://ghcr.io/democratic-csi/charts/democratic-csi
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: democratic-csi
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: local-path-provisioner
    controller:
      strategy: node
      externalProvisioner:
        image:
          registry: registry.k8s.io/sig-storage/csi-provisioner
          tag: v5.2.0
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1
      externalResizer:
        enabled: false
      externalAttacher:
        enabled: false
      externalSnapshotter:
        enabled: false
    csiDriver:
      name: local-hostpath.cluster.local
      storageCapacity: true
      attachRequired: false
      fsGroupPolicy: File
    storageClasses:
      - name: local-hostpath
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
    driver:
      config:
        driver: local-hostpath
        local-hostpath:
          shareBasePath: &storagePath /var/mnt/ssd/democratic-csi/local
          controllerBasePath: *storagePath
          dirPermissionsMode: "0770"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0
    node:
      hostPID: true
      driver:
        image:
          registry: ghcr.io/democratic-csi/democratic-csi
          tag: v1.9.3
        extraVolumeMounts:
          - name: local-hostpath
            mountPath: *storagePath
            mountPropagation: Bidirectional
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
      extraVolumes:
        - name: local-hostpath
          hostPath:
            path: *storagePath
            type: DirectoryOrCreate
