---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notifiarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: notifiarr-secret
    template:
      engineVersion: v2
      data:
        DN_API_KEY: "{{ .notifiarr_api_key }}"
        DN_UI_PASSWORD: "{{ .notifiarr_password }}"
        DN_PLEX_URL: "http://plex.default.svc.cluster.local:32400"
        DN_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        DN_QBIT_0_NAME: "qbittorrent-kube"
        DN_QBIT_0_URL: "http://qbittorrent.default.svc.cluster.local:8080"
        DN_QBIT_0_USER: "{{ .qbittorrent_username }}"
        DN_QBIT_0_PASS: "{{ .qbittorrent_password }}"
        DN_RADARR_0_NAME: "radarr-kube"
        DN_RADARR_0_URL: "http://radarr.default.svc.cluster.local:8080"
        DN_RADARR_0_API_KEY: "{{ .RADARR_API_KEY }}"
        DN_SONARR_0_NAME: "sonarr-kube"
        DN_SONARR_0_URL: "http://sonarr.default.svc.cluster.local:8080"
        DN_SONARR_0_API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: qbittorrent
      rewrite:
        - regexp:
            source: "(.*)"
            target: "qbittorrent_$1"
    - extract:
        key: notifiarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "notifiarr_$1"
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: plex
