apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-secret
stringData:
    DN_API_KEY: ENC[AES256_GCM,data:V9pugBAT/7dKRYKVQ8cuouL0RtripnICLooYHPDnysXSzOQ2,iv:tZMFix2FhnZpRGHVhCYgf9Ows4tlIlCBBTpuif41/2o=,tag:qBLYYTmVl6esDz2TOtbrHg==,type:str]
    DN_UI_PASSWORD: ENC[AES256_GCM,data:sl/rkP2lpcO+8ZDqgMRQSw==,iv:NORflJX45TDvp/W63+Ty9tGUcjeckReBkI0WGgzxGDM=,tag:1HgDwoETt0cDsrZOaRx3jg==,type:str]
    DN_PLEX_URL: ENC[AES256_GCM,data:V+4Lvkxvh3lPicKuHuZX22nJ+PVJyY737lBtMe98lDK+xU1nzBfxa+d1gA==,iv:IggAHIG3TYTuzSuyYj/UfXYEXqas/6EepRsfKhEG8+4=,tag:v4oJfin/NaRJxfiRMiA94Q==,type:str]
    DN_PLEX_TOKEN: ENC[AES256_GCM,data:t+x+karh9K8nQasZvt92nxywXYY=,iv:F0pJEsCP/HrJnpXI+2vJxmnu9qBlpbPU6rUmRB7bh/E=,tag:IZcF9GAJbhoUS2Uk3dlQ3A==,type:str]
    DN_QBIT_0_PASS: ENC[AES256_GCM,data:BdEkh493jdt52e0bRFJpu1IG4Nw=,iv:M97oJltZN3AgM7m1Q2x0jCnArzZXK5N6ylKIMFjSQA0=,tag:Pgjhum4t6B14scfndIaQhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL093QnREYWxoREIvUENU
            YjVobDYwTGhhZ2ova3A4ZWFxbjBhUmNpam5nCldMUzVuWExHWXdYQlhGcklxWGE2
            VFd1cEJCTU10L1lWOWtpUS9jM25nK1EKLS0tIHBnWFdrUHVsRGhra1NBZVp4dk9a
            eW1PbHlNczl0ek1pZTMwQnpGbWtpWHMKqQZJzsPC04gvt/xq0tCBbFrWdrbGpTAD
            ZN7skiwyEfocX35cDozdyIVpsw00MTk5odU5W8tEcGGP2hvjRC0mFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T20:52:24Z"
    mac: ENC[AES256_GCM,data:M/lqmCkoKdcndHuWKl5Vtp2UVAzdrvwXAeQ3q6X6HyIfJ/KDtic+7TfNakLfYYZehlHNmsWd0NutpkJBdpVOzXif1HyOrfem7ZQJsbsWeD4LncLSXEP5zcB29mDdd/pXLgAxeHZdBe7w8WmXeEkEC/NOZau4YA5uIk8v9PilGjA=,iv:eZ4n5HCuvtPWV0Websq/lVU4GFhxHIkIyGj3lCH2/Go=,tag:8R6h/FXNJS6FXWqB/03UZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
