apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-secret
stringData:
    DN_API_KEY: ENC[AES256_GCM,data:ow6hVXuGiAfZYm3KiTiYaVQwFvSpTwCsI2VBpakfg2URAVmE,iv:SyGiIgyqcXvGF4OX/g+EdyXRNJzIWIoZ5tuD12GiHeU=,tag:3TmfttNiUzlrDVS9oHXnvA==,type:str]
    DN_UI_PASSWORD: ENC[AES256_GCM,data:+zwTWBS7iYA0jCovOjiVGg==,iv:ys7A7uIVZWY1ZW9yU/Jl51+lDBSlby0iVL5FZUZyHWE=,tag:oErB0aSGLHD6cSez3X2QvA==,type:str]
    DN_PLEX_URL: ENC[AES256_GCM,data:tpDygb7hzbf8PRGcTGov/921y3hPTqVYMb1QRcLije6M/CC8S0Rygx8FSA==,iv:XUGpNlqqUdghiHkjpMANSI7F89N7QbVqiqQS/CeD7Pk=,tag:bXmnDSnuXUfqVZy5rKlpxw==,type:str]
    DN_PLEX_TOKEN: ENC[AES256_GCM,data:FrYpZmCeZgyLgQyxQyYHMxBf67M=,iv:tmNv4NwpTxjg4hahVL2lZ2pL36J691rR7Yoft4+X3ks=,tag:1hXd4vADExD2JS3dqFjQMg==,type:str]
    DN_QBIT_0_PASS: ENC[AES256_GCM,data:zf0Jf1fYFk0ulv2z,iv:V419jWgA399UDPfDZ8L9t/BEbGktu5osopgNA+DILBA=,tag:oWFppmHV8dkCXU+xs+Zr5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN29HZWEyanhiUElOancv
            YnpyOGZ5TlcwdWI3U0MxVlZ5RGlOSmlrZ1EwCm9HQ25OVE45NDVHNHB3UEF4WVFE
            VW1CbTcrREVkK2h3elJRcDVJMlBXTHcKLS0tIGpBNlVpbWs0ZTlyUGhPQ3lzR1JB
            TkEzUk5ycVhFZFRLOHpmcGZTTkIyZlEKQximvaK1lRFkgHKXtYN5XTruwLhdKaKy
            fUtV22Pyw62SiM42Vkafi/GEDCxo0d0zGvc25GVgy3UOJl7F+XWJDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-02T15:14:12Z"
    mac: ENC[AES256_GCM,data:xUWGzmd5TkqSPqx3tRguac+kSPVA+ClTHmY1JnRjdPRd4T1qsJKryvYDTKrOHYsBAUhrlBUaDhF3JLK4/DpqVFeqeW9IM9F9P7RIfOQ4R6TRQnwNfK1znWGYOWns7INjkZ2vVgKtUk7aCmc9R54aGoU4C6xXw4dbu2FuttAH1Bo=,iv:bpfJP9ei+hefsXIwdAzeRhTVvKrDoZWpY4F0DGXkLAo=,tag:FFduJfj62/N5m9cPdWUK/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
