apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-secret
stringData:
    DN_API_KEY: ENC[AES256_GCM,data:v3Rwva9hNVN1+RkNoyxwDEtlPWmtcgBwGM6wPCnRJnrr0+wF,iv:3GPun+ygjgj6MoIKXz8R7RzwO/mv9waDFKgPfk72zGc=,tag:8yHqNiSoTLDmIwhsH+LjwQ==,type:str]
    DN_UI_PASSWORD: ENC[AES256_GCM,data:srSJsaUHBzbd5gJvNB42cA==,iv:4ryRda5jFxdz6JFmvcPwO/ajtBtyRZD+uZuoTZQRHbE=,tag:9O4jmHNU3tLwBEtEwlpykw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU0hlSmJnUFUvM3dZRDB5
            dFVYVldhQjkyMnBQUzdMZkczYzBncUpwMEZRCnpQUGg1N3J3USt3cUNXeUxoRzRO
            eVBCeE5ZdnhJczR5YXExcDFvMGt1STAKLS0tIHU1MFBYYnlKbnNDMDVaS1djb3p4
            ZnlOV2lSTHZ4RldGNmV2ZGtpZFNEZG8KPGpKEaUh4CSkM2xxSrmLEUByUq/20e82
            HTfcfC0ivY/pPgK1tdKRysq7bI5ltYpQISGhVslrwmbPN/CtSEZCNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T16:08:11Z"
    mac: ENC[AES256_GCM,data:TLm20NwbzWCKgtcICgUnGZycL0dtt+IhI3FmRmNZ6Eudzse+prE6SU5icCJN2cN7l2CGDDOlV0BthQelonUAstUR1jTDFggSSTZuSLLc47nE7+zcHs4T7t9l6ECSJI8hEFtwf8fjTKc/OQVkzHniOE70xX0xRPSlgR4VLQefyxw=,iv:YIoWYzeNjsZ5MT+PkU7Qw2Ye7xv/+OKZBr+Vq2/6N6g=,tag:TklkX5n+shPnNKUNMyg2+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
