---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

vars:
  # Directories
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  INFRA_DIR: "{{.ROOT_DIR}}/infrastructure"
  ANSIBLE_DIR: "{{.INFRA_DIR}}/ansible"
  SCRIPTS_DIR: "{{.KUBERNETES_DIR}}/bootstrap/scripts"
  TALOS_DIR: "{{.KUBERNETES_DIR}}/bootstrap/talos"
  # Files
  AGE_FILE: "{{.ROOT_DIR}}/age.key"
  KUBECONFIG_FILE: "{{.ROOT_DIR}}/kubeconfig"
  INFRA_SECRETS_FILE: "{{.INFRA_DIR}}/secrets.sops.yaml"

env:
  KUBECONFIG: "{{.KUBECONFIG_FILE}}"
  SOPS_AGE_KEY_FILE: "{{.AGE_FILE}}"
  INFRA_SECRETS_FILE: "{{.INFRA_SECRETS_FILE}}"

includes:
  bootstrap: .taskfiles/bootstrap
  kubernetes: .taskfiles/kubernetes
  talos: .taskfiles/talos
  volsync: .taskfiles/volsync
  ansible: .taskfiles/ansible/Taskfile.yaml

tasks:
  default:
    cmd: task --list
    silent: true
