---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: audiobookshelf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: audiobookshelf-secret
    template:
      engineVersion: v2
      data:
        # These don't work yet
        AUDIOBOOKSHELF_OIDC_DISCOVERY_URL: "https://sso.${SECRET_DOMAIN}/application/o/audiobookshelf/.well-known/openid-configuration"
        AUDIOBOOKSHELF_OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        AUDIOBOOKSHELF_OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        TOKEN_SECRET: "{{ .JSON_TOKEN }}"
  dataFrom:
    - extract:
        key: audiobookshelf
