---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: APP_NAME
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: APP_NAME-secret
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        APP_ENV: "{{ .APP_1PASS_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: app
      rewrite:
        - regexp:
            source: "(.*)"
            target: "app_$1"
