---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maybe
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: maybe-secret
    template:
      engineVersion: v2
      data:
        OPENAI_ACCESS_TOKEN: "{{ .OPENAI_ACCESS_TOKEN }}"
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
  dataFrom:
    - extract:
        key: maybe
