---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app maybe
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
  values:
    controllers:
      maybe:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          web:
            image:
              repository: ghcr.io/maybe-finance/maybe
              tag: latest@sha256:08109a563c042cd67d14ada8960efdaa0f5045bbfb2df89f01c5a6a9fd3e1340
            env: &env
              TZ: "Europe/Warsaw"
              SELF_HOSTED: "true"
              REDIS_URL: "redis://dragonfly.database.svc.cluster.local:6379/5"
              # POSTGRES
              POSTGRES_USER: *app
              POSTGRES_DB: *app
              DB_HOST: maybe-pgbouncer.default.svc
              DB_PORT: "5432"
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: maybe-pguser-maybe
                    key: password
            envFrom:
              - secretRef:
                  name: maybe-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: [ "ALL" ] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
          worker:
            image:
              repository: ghcr.io/maybe-finance/maybe
              tag: latest@sha256:08109a563c042cd67d14ada8960efdaa0f5045bbfb2df89f01c5a6a9fd3e1340
            command: ["bundle", "exec", "sidekiq"]
            env: *env
            envFrom:
              - secretRef:
                  name: maybe-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: [ "ALL" ] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      web:
        controller: *app
        ports:
          http:
            port: 3000
    route:
      app:
        hostnames: [ "{{ .Release.Name }}.exelent.click" ]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: maybe.png
          gethomepage.dev/name: Maybe Finance
          gethomepage.dev/group: "Home Apps"
          gethomepage.dev/description: "Investment Management"
          gethomepage.dev/weight: "6"
    persistence:
      storage:
        existingClaim: *app
        globalMounts:
          - path: /rails/storage
