---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./stakater.yaml
  - ./cloudnative-pg.yaml
  - ./longhorn.yaml
  - ./backube.yaml
  - ./piraeus.yaml
  - ./democratic-csi.yaml
