apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:gogMGidvHW9zw+hGGMnvBrhD6s4qIHIYXji3coPwQ827UEO8,iv:N25wj9fahp23xkVVrVJcnAEA9abT8DUCadqtb53Q5Ec=,tag:KgJ0btli2gDAA87KpOKEIg==,type:str]
    credentials.json: ENC[AES256_GCM,data:uWIBdsL9fMIFWKJAzK6C2tmAynRbBK8DcDbkpzAqE6KDJ7Mbk7AmOQ6jA0oNwjXS6P6gW5g1wKJL7HmnSrUkAHLg+AYhcjON4/v/Cmuo2JRMJFUM9eUFRGa9xky99l93DRhXBMJU99tUBRtehx6H2kFgEEJJ0MQEUSs4G9Nz+pdg0yNGvaynBvgPKpw5s6oaahe5Hjo9AFv4IMYVTG4pA0251fqqcgGdAI6K+nQh6A==,iv:RZUWsk+tN+ZFbyYwxLsHzcpeJZCtWRIPxTRL/OHR7ck=,tag:fUpA8tWLbugCLwKb6Kh95g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWWtoNUtRWWlkVWJtZjJq
            NzRtOTFVNzl0WlIrei9OeWZucHFoS2oyV2xJCmd6bTVIZzE5NHE5OXk2eVNaWnBP
            V2hwTVVUYThkT1doWWlodVhsMXozVjAKLS0tIEozc245dnlGTmtjR0hsdlZLQ2w2
            djVWUHhidmFQMDQ4eWFJdzQwRzhoSmsKinia/3UsfE5kXGhqzOFljaFgQOsZLtGU
            +iXpBQFdY4gNJBMnsc1WprcmR0SQ5KqyKJtv98XHuKNo6057yyxs4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-17T21:45:25Z"
    mac: ENC[AES256_GCM,data:RtqS8HKq2GxliN7gKhgMFhHOJatc2vMHV+d0rfpvdAFSIAzRer0eaxn40VkKH2S8zECQ7LXua1rkf5U1E+gpm5+KCNzsClHVGmkwFzIlsfEFXus7GoZ+kecAjI1OueIubHV+HD/6XqoOuBqt1L+G7x0sybwaj6iZJfgl7qLMDms=,iv:gqycv2viknPZzcitNe63IwjCZQ0obgoWXqh1cb8A77M=,tag:JxbbqBq7J8FuOeCA9JJf6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
