---
kubernetes:
  children:
    controllers:
      hosts:
        "k3s-control-1":
          ansible_user: "root"
          ansible_host: "192.168.20.51"
        "k3s-control-2":
          ansible_user: "root"
          ansible_host: "192.168.20.52"
        "k3s-control-3":
          ansible_user: "root"
          ansible_host: "192.168.20.53"
        "rpi5":
          ansible_user: "pi"
          ansible_host: "192.168.20.3"
