---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmproxy_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMProxy
metadata:
  name: litellm
spec:
  # renovate: datasource=docker depName=ghcr.io/berriai/litellm
  image: ghcr.io/berriai/litellm:v1.102.1@sha256:87f34979b9f8cb274fac90ca8a4fdda07d8480de22755562a26adeb95ce20d02
  replicas: 1
  generalSettings:
    health_check_endpoint: /v1/health
  routerSettings:
    routing_strategy: simple-shuffle
    redis_host: os.environ/REDIS_HOST
    redis_port: os.environ/REDIS_PORT
    redis_password: os.environ/REDIS_PASSWORD
    num_retries: 3
    timeout: 600
  litellmSettings:
    success_callback:
      - prometheus
    prometheus_adapter: true
    cache: true
    cache_params:
      type: redis
      host: os.environ/REDIS_HOST
      port: os.environ/REDIS_PORT
      password: os.environ/REDIS_PASSWORD
    drop_params: true
    merge_reasoning_content_in_choices: true
  env:
    - name: LITELLM_LOG
      value: INFO
    - name: LITELLM_MODE
      value: PRODUCTION
    - name: REDIS_HOST
      value: dragonfly-litellm.database.svc.cluster.local
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: litellm-secret
          key: REDIS_PASSWORD
    - name: LITELLM_MASTER_KEY
      valueFrom:
        secretKeyRef:
          name: litellm-secret
          key: LITELLM_MASTER_KEY
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: postgres-litellm-app
          key: uri
    - name: PROXY_BASE_URL
      value: https://litellm.exelent.click
    - name: GENERIC_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: litellm-secret
          key: GENERIC_CLIENT_ID
    - name: GENERIC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: litellm-secret
          key: GENERIC_CLIENT_SECRET
    - name: GENERIC_AUTHORIZATION_ENDPOINT
      value: https://sso.exelent.click/application/o/authorize/
    - name: GENERIC_TOKEN_ENDPOINT
      value: https://sso.exelent.click/application/o/token/
    - name: GENERIC_USERINFO_ENDPOINT
      value: https://sso.exelent.click/application/o/userinfo/
    - name: GENERIC_SCOPE
      value: openid email profile
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 2Gi
  service:
    type: ClusterIP
    port: 4000
  route:
    hostnames:
      - litellm.exelent.click
    parentRefs:
      - name: envoy-internal
        namespace: network
