---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent-tools-files-cleaner
spec:
  chartRef:
    kind: OCIRepository
    name: qbittorrent-tools-files-cleaner
  interval: 1h
  dependsOn:
    - name: qbittorrent
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          # run it after qbit_manage
          schedule: "5 * * * *"
          timeZone: "Europe/Warsaw"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          main:
            image:
              repository: ghcr.io/maksimshakavin/qbit-torrent-files-cleaner
              tag: 0.2.0@sha256:4363aa7a11655ee517326fd27be8064d16d53075156c472087b6fe7b8fb8f367
            command:
              - qbit-torrent-files-cleaner
            args:
              - --config
              - &config /config/config.yaml
        pod:
          restartPolicy: OnFailure
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config-file:
        type: secret
        name: qbit-torrent-files-cleaner-secret
        globalMounts:
          - path: *config
            subPath: config.yaml
      downloads:
        type: nfs
        server: "nas.exelent.click"
        path: "/volume1/kubernetes"
        globalMounts:
          - path: /data
