---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: firefly-secret
    template:
      engineVersion: v2
      data:
        SITE_OWNER: "{{ .email }}"
        APP_KEY: "{{ .FIREFLY_API_KEY }}"
        DB_HOST: &dbHost postgres-cluster-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USERNAME: &dbUser "{{ .FIREFLY_POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .FIREFLY_POSTGRES_PASSWORD }}"
        DB_DATABASE: &dbName firefly
        STATIC_CRON_TOKEN: "{{ .STATIC_CRON_TOKEN }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: firefly
