---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: snapshot-controller
      version: 3.0.5
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controller:
      volumeSnapshotClasses:
        - name: longhorn-snapclass
          annotations:
            snapshot.storage.kubernetes.io/is-default-class: "true"
          driver: driver.longhorn.io
          deletionPolicy: Delete
          # Ref: https://github.com/longhorn/longhorn/issues/2534#issuecomment-1010508714
          parameters:
            type: snap
      serviceMonitor:
        create: true
    webhook:
      enabled: false
