---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
spec:
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/postgres/credentials-mirror
    - ../../../../components/zeroscaler
  dependsOn:
    - name: paperless-postgres
      namespace: default
    - name: paperless-dragonfly
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/paperless/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  postBuild:
    substitute:
      APP: paperless
      APP_NAMESPACE: default
      KOPIUR_CAPACITY: 1Gi
