---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-secret
    template:
      engineVersion: v2
      data:
        CF_API_TOKEN: "{{ .CF_API_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflare
