---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: postgres-cluster-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .GATUS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .GATUS_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        DISCORD_WEBHOOK: "{{ .GATUS_DISCORD_WEBHOOK }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: gatus
    - extract:
        key: discord
