---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valheim-discord
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: valheim-discord-secret
    template:
      engineVersion: v2
      data:
        discordconnector.cfg: |
          [Main Settings]

          ## Override the username of all webhooks for this instance of Discord Connector. If left blank, the webhook will use the default name (assigned by Discord).
          ## This setting will be used for all webhooks unless overridden by a specific webhook username override setting.
          # Setting type: String
          # Default value:
          Default Webhook Username Override =

          ## Discord channel webhook URL. For instructions, reference the 'MAKING A WEBHOOK' section of
          ## Discord's documentation: https://support.Discord.com/hc/en-us/articles/228383668-Intro-to-Webhook
          # Setting type: String
          # Default value:
          Webhook URL = {{ .VALHEIM_DISCORD_WEBHOOK }}

          ## Specify a subset of possible events to send to the primary webhook. Previously all events would go to the primary webhook.
          ## Format should be the keyword 'ALL' or a semi-colon separated list, e.g. 'serverLifecycle;playerAll;playerFirstAll;leaderboardsAll;'
          ## Full list of valid options here: https://discord-connector.valheim.games.nwest.one/config/main.html#webhook-events
          # Setting type: String
          # Default value: ALL
          Webhook Events = serverStart;serverShutdown;playerJoin;playerLeave;playerDeath;

          ## Override the username of the webhook. If left blank, the webhook will use the default name.
          # Setting type: String
          # Default value:
          Webhook Username Override =

          ## Override the avatar of the primary webhook with the image at this URL.
          ## If left blank, the webhook will use the avatar set in your Discord server's settings.
          # Setting type: String
          # Default value:
          Webhook Avatar Override =

          ## Discord channel webhook URL. For instructions, reference the 'MAKING A WEBHOOK' section of
          ## Discord's documentation: https://support.Discord.com/hc/en-us/articles/228383668-Intro-to-Webhook
          # Setting type: String
          # Default value:
          Secondary Webhook URL =

          ## Specify a subset of possible events to send to the secondary webhook.
          ## Format should be the keyword 'ALL' or a semi-colon separated list, e.g. 'serverLaunch;serverStart;serverSave;'
          ## Full list of valid options here: https://discord-connector.valheim.games.nwest.one/config/main.html#webhook-events
          # Setting type: String
          # Default value: ALL
          Secondary Webhook Events = ALL

          ## Override the username of the secondary webhook.
          ## If left blank, the webhook will use the default username set in the main config.
          # Setting type: String
          # Default value:
          Secondary Webhook Username Override =

          ## Override the avatar of the secondary webhook with the image at this URL.
          ## If left blank, the webhook will use the avatar set in your Discord server's settings.
          # Setting type: String
          # Default value:
          Secondary Webhook Avatar Override =

          ## Enable this setting to listen to debug messages from the mod. This will help with troubleshooting issues.
          # Setting type: Boolean
          # Default value: false
          Log Debug Messages = false

          ## Enable this setting to use embeds in the messages sent to Discord. Currently this will affect the position details for the messages.
          # Setting type: Boolean
          # Default value: false
          Use fancier discord messages = true

          ## It may be that you have some players that you never want to send Discord messages for. Adding a player name to this list will ignore them.
          ## Format should be a semicolon-separated list: Stuart;John McJohnny;Weird-name1
          # Setting type: String
          # Default value:
          Ignored Players =

          ## It may be that you have some players that you never want to send Discord messages for. This option lets you provide a regular expression to filter out players if their name matches.
          ## Format should be a valid string for a .NET Regex (reference: https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference)
          # Setting type: String
          # Default value:
          Ignored Players (Regex) =

          ## Disable this setting to disable any positions/coordinates being sent with messages (e.g. players deaths or players joining/leaving). (Overwrites any individual setting.)
          # Setting type: Boolean
          # Default value: true
          Send Positions with Messages = true

          ## Disable this setting to disable all stat collection. (Overwrites any individual setting.)
          # Setting type: Boolean
          # Default value: true
          Collect Player Stats = true

          ## Disable this setting to disable all extra announcements the first time each player does something. (Overwrites any individual setting.)
          # Setting type: Boolean
          # Default value: true
          Announce Player Firsts = true

          ## Choose a method for how players will be separated from the results of a record query (used for statistic leader boards).
          ## Name: Treat each CharacterName as a separate player
          ## PlayerId: Treat each PlayerId as a separate player
          ## NameAndPlayerId: Treat each [PlayerId:CharacterName] combo as a separate player
          # Setting type: RetrievalDiscernmentMethods
          # Default value: PlayerId
          # Acceptable values: PlayerId, Name, NameAndPlayerId
          How to discern players in Record Retrieval = PlayerId

          ## Enable this setting to have shouts which are performed by other mods/the server/non-players to be sent to Discord as well.
          ## Note: These are still subject to censure by the muted player regex and list.
          # Setting type: Boolean
          # Default value: false
          Send Non-Player Shouts to Discord = false

          ## Enable this setting to allow messages sent to Discord to mention @here and @everyone. Per the Discord API, these share the same setting.
          ## Note: There is no filtering in place to prevent abuse of these mentions (e.g. in a shout or player's name).
          # Setting type: Boolean
          # Default value: false
          Allow @here and @everyone mentions = false

          ## Enable this setting to allow messages sent to Discord to mention roles. Roles mentioned this way use the format `<@&role_id>`
          ## Note: There is no filtering in place to prevent abuse of these mentions (e.g. in a shout or player's name).
          # Setting type: Boolean
          # Default value: true
          Allow @role mentions = true

          ## Enable this setting to allow messages sent to Discord to mention users. Users mentioned this way use the format `<@user_id>`
          ## Note: There is no filtering in place to prevent abuse of these mentions (e.g. in a shout or player's name).
          # Setting type: Boolean
          # Default value: true
          Allow @user mentions = true

          ## A semicolon-separated list of role IDs that are allowed to be mentioned in messages sent to Discord. These are just a number (no carets), e.g. `123;234`
          ## Note: This setting is overshadowed if 'Allow @role mentions` is enabled, and only when that is disabled will these roles still be allowed to be mentioned.
          # Setting type: String
          # Default value:
          Allowed Role Mentions =

          ## A semicolon-separated list of user IDs that are allowed to be mentioned in messages sent to Discord. These are just a number (no carets), e.g. `123;234`
          ## Note: This setting is overshadowed if 'Allow @user mentions` is enabled, and only when that is disabled will these users still be allowed to be mentioned.
          # Setting type: String
          # Default value:
          Allowed User Mentions =
  dataFrom:
    - extract:
        key: discord
