---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: valheim
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: valheim-secret
    template:
      engineVersion: v2
      data:
        PASSWORD: "{{ .valheim_password }}"
        WEBHOOK_URL: "{{ .VALHEIM_DISCORD_WEBHOOK }}"
  dataFrom:
    - extract:
        key: valheim
      rewrite:
        - regexp:
            source: "(.*)"
            target: "valheim_$1"
    - extract:
        key: discord
