---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app valheim
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
  values:
    controllers:
      valheim:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          copy-discord-secret:
            image:
              repository: docker.io/library/alpine
              tag: 3.20.3
            command:
              - "sh"
              - "-c"
              - |
                mkdir -p /home/steam/valheim/BepInEx/config/games.nwest.valheim.discordconnector &&
                cp -f /temp-dir/discordconnector.cfg /home/steam/valheim/BepInEx/config/games.nwest.valheim.discordconnector/discordconnector.cfg
        containers:
          app:
            image:
              repository: ghcr.io/mbround18/valheim
              tag: 3.0.4
            env:
              TZ: "${TIMEZONE}"
              NAME: "Shojkborg"
              WORLD: "Shokushkino"
              PUBLIC: "False"
              TYPE: "BepInEx"
              ENABLE_CROSSPLAY: 0
              HTTP_PORT: &port 1025
              AUTO_BACKUP: 1
              AUTO_BACKUP_ON_UPDATE: 1
              AUTO_BACKUP_ON_SHUTDOWN: 1
              AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS: 1
              ADDRESS: "127.0.0.1:2457"
              AUTO_UPDATE: 1
              AUTO_UPDATE_PAUSE_WITH_PLAYERS: 1

              # It MUST be a link with a command and a new line at the end to be valid.
              MODS: |
                https://thunderstore.io/package/download/ValheimModding/Jotunn/2.20.2/,
                https://thunderstore.io/package/download/JereKuusela/Server_devcommands/1.81.0/,
                https://thunderstore.io/package/download/nwesterhausen/DiscordConnector/2.3.1/

            envFrom:
              - secretRef:
                  name: valheim-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                memory: 4Gi
                cpu: 400m
              limits:
                memory: 7Gi
    defaultPodOptions:
      securityContext:
        runAsUser: 111
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: valheim
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "${CLUSTER_LB_VALHEIM}"
        ports: &ports
          http:
            port: *port
          gameplay:
            enabled: true
            port: 2456
            protocol: UDP
          auth:
            enabled: true
            port: 2457
            protocol: UDP
          voip:
            enabled: true
            port: 2458
            protocol: UDP
      playit:
        controller: valheim
        type: ClusterIP
        clusterIP: 10.96.237.67 # FIXME: Remove if/when playit supports hostname tunnel endpoints
        ports: *ports
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        className: external
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      server:
        existingClaim: *app
        globalMounts:
          - path: /home/steam/valheim
            readOnly: false
      saves:
        type: nfs
        server: "${NAS_URL}"
        path: "${NAS_PATH}/valheim/saves"
        globalMounts:
          - path: /home/steam/.config/unity3d/IronGate/Valheim
      backup:
        type: nfs
        server: "${NAS_URL}"
        path: "${NAS_PATH}/valheim/backup"
        globalMounts:
          - path: /home/steam/backups
      # Workaround to overcome that k8s secrets are always readOnly. Mount secret to a emptyDir, then copy it with init
      # container to the required path
      data:
        type: emptyDir
        globalMounts:
          - path: /temp-dir
      discord-config:
        type: secret
        name: valheim-discord-secret
        globalMounts:
          - path: /temp-dir/discordconnector.cfg
            subPath: discordconnector.cfg
            readOnly: false
