---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app valheim
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
  values:
    controllers:
      valheim:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mbround18/valheim
              tag: 3.0.3
            env:
              TZ: "${TIMEZONE}"
              NAME: "Shojkkborg"
              WORLD: "Shokushkino"
              PUBLIC: "False"
              TYPE: "ValheimPlus"
              ENABLE_CROSSPLAY: "True"
              HTTP_PORT: &port 1025
              AUTO_BACKUP: 1
              AUTO_BACKUP_ON_UPDATE: 1
              AUTO_BACKUP_ON_SHUTDOWN: 1
            envFrom:
              - secretRef:
                  name: valheim-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: *port
                  initialDelaySeconds: 320
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup: *probes
            resources:
              requests:
                memory: 4Gi
                cpu: 200m
              limits:
                memory: 7Gi
    service:
      app:
        controller: valheim
        ports:
          http:
            port: *port
          gameplay:
            enabled: true
            port: 2456
            protocol: UDP
          auth:
            enabled: true
            port: 2457
            protocol: UDP
          voip:
            enabled: true
            port: 2458
            protocol: UDP
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        className: external
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      server:
        existingClaim: *app
        globalMounts:
          - path: /home/steam/valheim
      saves:
        type: nfs
        server: "${NAS_URL}"
        path: "${NAS_PATH}/valheim/saves"
        globalMounts:
          - path: /home/steam/.config/unity3d/IronGate/Valheim
      backup:
        type: nfs
        server: "${NAS_URL}"
        path: "${NAS_PATH}/valheim/backup"
        globalMounts:
          - path: /home/steam/backups
