---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr
spec:
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/postgres/credentials-mirror
    - ../../../../components/zeroscaler
  interval: 1h
  path: ./kubernetes/apps/default/radarr/app
  dependsOn:
    - name: longhorn
      namespace: storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  postBuild:
    substitute:
      APP: radarr
      APP_NAMESPACE: default
      KOPIUR_CAPACITY: 1Gi
