---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app APP_NAME
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/internal
    - ../../../../components/volsync
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/default/APP_NAME/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
