---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-${APP}
spec:
  instances: ${POSTGRES_REPLICAS:=3}
  imageName: ${POSTGRES_IMAGE:=ghcr.io/cloudnative-pg/postgresql:18-standard-trixie}
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  minSyncReplicas: 1
  maxSyncReplicas: 1
  resources:
    requests:
      memory: 256Mi
  storage:
    storageClass: local-hostpath
    size: ${POSTGRES_SIZE:=5Gi}
  affinity:
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  postgresql:
    parameters:
      max_connections: "500"
      max_wal_size: "5GB"
      synchronous_commit: "on"
  bootstrap:
    initdb:
      database: ${APP}
      owner: ${APP}
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: postgres-${APP}
        serverName: ${APP}
  monitoring:
    enablePodMonitor: true
