---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mealie
spec:
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/postgres/credentials-mirror
  dependsOn:
    - name: mealie-postgres
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/mealie/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  postBuild:
    substitute:
      APP: mealie
      APP_NAMESPACE: default
      KOPIUR_CAPACITY: 3Gi
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mealie-postgres
spec:
  components:
    - ../../../../../components/postgres
  dependsOn:
    - name: cnpg-barman-plugin
      namespace: database
    - name: onepassword
      namespace: external-secrets
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/default/mealie/db/postgres
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
  postBuild:
    substitute:
      APP: mealie
      APP_NAMESPACE: default
