---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki-secret
    template:
      engineVersion: v2
      data:
        S3_BUCKET: "{{ .MINIO_LOKI_BUCKET }}"
        S3_ACCESS_KEY: "{{ .MINIO_LOKI_ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ .MINIO_LOKI_SECRET_KEY }}"
        S3_REGION: us-east-1
  dataFrom:
    - extract:
        key: minio
