---
all:
  hosts:
  children:
    proxmox:
      hosts:
        proxmox-1:
          ansible_host: 192.168.0.41
        proxmox-2:
          ansible_host: 192.168.0.42
        proxmox-3:
          ansible_host: 192.168.0.43
      vars:
        ansible_user: root
        sops: "{{ lookup('community.sops.sops', lookup('env', 'INFRA_SECRETS_FILE')) | ansible.builtin.from_yaml }}"
