# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
stringData:
    #ENC[AES256_GCM,data:ySzRKQ==,iv:F5BlRaYlDJ8RavRDCVZ/alAH/PZL9d8bnf+McILidoM=,tag:DHjIZWUb889wOn35fmUa5g==,type:comment]
    RADARR__API_KEY: ENC[AES256_GCM,data:mBQYgzyO2tRAU8YgUXSbSDdOOhEmr1w8vyytI4UZqYQ=,iv:rT+gPoYl68H0cFJSE/ffZucdAgm4eimH/C+mMyfTM9A=,tag:mX8zbIA3PEHddiB8R4C+mg==,type:str]
    RADARR__POSTGRES_HOST: ENC[AES256_GCM,data:kPFfGMxMU/f9XWSZvf+e6PZeLrTHGiYXPzUYr02h8q7PYQXtkqDbXLDidrd9ag==,iv:IBXegqulUWnz7LQedzV4N21aZ0dO1uERagrlaownMY4=,tag:8h4FCuAP449LEN+dK4QZBg==,type:str]
    RADARR__POSTGRES_PORT: ENC[AES256_GCM,data:vicoVw==,iv:D7ZiDnQYFe+pcGarQzL6fKAKoggOxyuab4veiCGCsyk=,tag:3kgLpDcuYEG6Kve19D+IQg==,type:str]
    RADARR__POSTGRES_USER: ENC[AES256_GCM,data:8vRTDajI,iv:B5obYalZbHJe/THDn1aAj2tFhrh5ogXtanQ/m5Nj4Dk=,tag:GSBCRQDNTS2VKbPBOFE0oA==,type:str]
    RADARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:j5GsAUuPDBP0maQub5kxqw==,iv:il4/kFT3R8exzSAwc6bWBJUc8UcVE9U+P7pRK1C+zDE=,tag:5Y3rEMRUYqLlspPlXKvhmg==,type:str]
    RADARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:jTd2BdMT5aCX3Qs=,iv:PghVEdRCdc9vL8gn39CQqgLcd5z5sWuG7QEE19Zg2hY=,tag:C8OgvujQWkrDYabZl4gnxQ==,type:str]
    RADARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:MRiKU3rG+PW7LQ==,iv:dDzi8Jt2EMBj8uPFehwETV6Tj3oBjRqslsrq/uh4UO0=,tag:L3U7tRO2q0Rpnu0bvC05Eg==,type:str]
    #ENC[AES256_GCM,data:kEsk30IwhK1PUjvA/QQ=,iv:9+xu4Q2z3z488jGSjTcgx0aq+Zdg0nqffFYN51wX0V8=,tag:P9Kt1DTG7lHAKP7nFIy+kQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:QjncQC41DhpX+iqqKbT8sJww8Ul5hA==,iv:8+0I2vx6/MjK9Y85NebXmagh5xRL6UVqa4M4jVZ0Y6M=,tag:3ojOc/JctoaAjGGDY8E+LA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:HBB0h8cFbUxI0KjCJEUgxEcXMGWzbY5GrXi1WuADcnT8S6mPAo2qmWKrg1EkAQ==,iv:mNt25dTa57DSgpGxOsdv81UidWO19T69eh9Ubn2iihY=,tag:wvm6lOJUPNv3KHo6yqJg6Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:S2RuoN9h,iv:/+kZzJodeD9qCQmEnS8xLv5YUEjgj5+DfkBLQe+2P88=,tag:1NdHCoIBTB/7zqUF8bd5BQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:vdFDkCtst5lG2Xi3AQ7v6w==,iv:RPV0edXxY5ni090NlW2DNEDbZ+NXd9Nk07L98veVsaM=,tag:gKzD2nUbfXp9nPzGFsUE+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeFU4bk4rSWtxTXBMR3RH
            RU15NjJaNE5IY2RBd2pTSVJmZElzNGxkS0JVClQ4MEc1STVsQmNGcjZ2QUs3alhp
            VUY4UG5QdGJIQ0ZBcWpPV0ZaSWtEck0KLS0tIHMrSlp5b0dmVTh1UWRXdW5tMHli
            OHdyMk9OeUlJZnNCQkt2bVRKVFZ4RDgKAmPoTweXh9hBr/mnLwgzazT4NZpjqIBe
            ZGIuiGLDbKEgNLlBWezmx6g1aypR+waVfmnUmBs+pKzov4lnK2skeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T17:54:04Z"
    mac: ENC[AES256_GCM,data:sM/b53tVCvaRVdoDI2Ax4gA5G5UmTXYgs6mQJBLvfiNJ/6CbDHM9PqetJoIH0PwCKqlUO5NaM41QQBntvbJ1L5vxJLrLagTanvUBIjp9T/+FlQeqaCXNs/Kkj4CHGGF37cHJ/rgalUkGNTZpfGqoSVcOcy+oAd7ovxtHkzeu3sU=,iv:DMbgmy4N6tEf76c9BPpdNDZOzha7i3j3s+Op0qWdNpY=,tag:rfWQvIRyOe9gUWXB0AZbtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
