---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Warsaw"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "192.168.20.0/24"
  CLUSTER_LB_QBITTORRENT: "192.168.20.64"
  CLUSTER_LB_PLEX: "192.168.20.65"
  NAS_URL: "192.168.20.5"
  RPI_URL: "192.168.20.3"
  NAS_PATH: "/volume1/kubernetes"
