apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:9YUm8BOmLfWPmPSnFfv4yqQ8whU4TaZbTQBo3wRspApYvWNqmroZ3EN6pGHcBLxDHGR2JhQ8SrDNps0dZwOJfk/a5Me2GRoDsNalx5zGF8bcHtNoPRrG1dNIw0heuw==,iv:QG3FEJh4TBSCo/fObNQqqGYWUKrXeNlwWcUaGXo0hxU=,tag:lSPMvF/VtrLxgf8mCQEvQw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:wIYcdMzbnNTbcV2LJA==,iv:0Uv+rP/oyYciSkNb7RQ5mF4iqHPVP1uBtT34ZhLowUc=,tag:+XQceahKYlYPKgeTnDiKSg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:RfWJZgnzIDbI2purDft7jjrrGJhjDdUxwg==,iv:XVTUbnM8CuXEe0UaZ4LadaPnj/pAC2YB+n34lDYC9mw=,tag:WlO3dsmY5SSAG1VQIqWrow==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:E/e0M+QKytLvZgD9U6egSGwV4qbpKVUV1ZUKaq2bd9S2FoDi,iv:CBzu//vbiSr3sxNd3Wz72o6/csx3AEU9lSN03Fzf4V8=,tag:ESOgRxclJqa/I+j30HwMhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d05DamV1TWNOc0o1aXoz
            Q0ltajRxWmEraDlsRE4veFhZdXpqNFZBM2tBCjFPZnhQNGlNQTUxQSt0U3oreFZJ
            T1RaSWVzVTNDUWFuOHBUbGNmbFdBSk0KLS0tIG9UNUlSdFd0emRuN2NGVzZiUjZy
            VGx5R1lKZU1aejkvUjZDcytvQkczalkKjKsV4X9HnVtQG80TpVctxHdio//g3vJN
            oD7AdZ0iGC3Z0W8VD9N7kLYIpB4BvC1QVP2cEVw6YW/9x+M2Y/to0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-17T21:45:25Z"
    mac: ENC[AES256_GCM,data:RUzvexrVSeRFAmzJvLKQkXdFft3erBN9ZOUPgMAl+RJr0cSu/x5EC2EyogxxD4KY9x25HeVI/u986rgovwWkm95vDVV8BT/xWk+x1QgsuUguY2eAY2tJaebgS4CoE607vUj9M7g0EfytoWpAKrmWuGFn+vRVfQfBVntYCHnoJhs=,iv:sIM7jCiYfyfcVR+HsG/jULWrYIXxIktd/hOx/v/3wcM=,tag:Yc/LoFIvemzf8/jJDj7+ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
