---
originRequest:
  originServerName: external.exelent.click

ingress:
  - hostname: exelent.click
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.exelent.click"
    service: *svc
  - service: http_status:404
