apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:QLoN/DxWFd+WGi+5jSo/uPOFk0M=,iv:57/QGdt6QU7gNBUhT6+sKlryeO463X7dTrC5kkSB4D8=,tag:TaN6uZx4ZvvkrIGekVQFWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNk8vTzJNeE9HWTh5bGdo
            ZTM2bktQUmhmQzhsVjBVWlI0MEtoN1JidkNZCnl3TkVWdDc3TDlrTDRnVEZwU2sx
            QlY1cllXRkphWUJSemNXbVhRcEVYcmsKLS0tIHhyT2NobDFkSXZjNVljVWJQeXhL
            QXNDOUROZDVMVHpLWXRVUWFMa3BhZTQKVRVh168ObeQIB5oPWWVb9u52Dc0GktG0
            uq1yUbAQ43xFWCi/C0ycFV+o+QtyeOSr76hJod9kx0+XIzrbj1LcJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T16:08:21Z"
    mac: ENC[AES256_GCM,data:RB1WumSeDrHgLYb7KXFQ7EIF0h7kRpO8/5fmP81NbFv1xCHsfDJcsUPYUWuwsw/uvcTTzZYvEgHcIqJrBlCSv5F/0I2c8Q9I/xekeiqKzW/97tmQqVdTZxaJ8WbbkWnM+FKsjZU1T5z1eDvxm6abnm93A28o5JDrq9rwRY7Hdsk=,iv:oeSVvcrtk2Iv2hOWVnDKerB0g42a1Cwtu1rfqTwxPBY=,tag:Pap7RBWc1oic/UQgHibIhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
