# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
stringData:
    #ENC[AES256_GCM,data:dGPYzQ==,iv:Z1N863Zz9KOVWZycZ62eX4yAVEYyxASI53mt4H6JoFQ=,tag:0dltD79MLfylvrP8PaXSsA==,type:comment]
    SONARR__API_KEY: ENC[AES256_GCM,data:P+2u/L3ZCn+2DncWopPjhq35OeDxOf/Mt8n2eoJ1xPk=,iv:KDgdf80F7SG9lgiTj5oiQQ82Ly3twcIC5dbZWHpG2F0=,tag:8gDqZSheKKKx5RQ8i4KaqA==,type:str]
    SONARR__POSTGRES_HOST: ENC[AES256_GCM,data:fxZ7ZNXjpS7ur62Sbm3mmC0PfOXbJN1bzQQ4xiRtU7USKL1JQbnyEQk+EDUwhA==,iv:INT+j8V2CoDADg7XsBk2MDJhJPJ1L40jXCMJCqR4C8A=,tag:DRq/JMtl14oLvGKmkSiTqg==,type:str]
    SONARR__POSTGRES_PORT: ENC[AES256_GCM,data:OFCacg==,iv:Fqxc2W06bPmDPCimImKFY6SThMjzzd5fhb2R8AgutnM=,tag:YUj8LqfU6e0uQdh0iIVjew==,type:str]
    SONARR__POSTGRES_USER: ENC[AES256_GCM,data:szO8i+ZF,iv:muiRjTcwYfpj9JClVprDu62MhqoLXR3qiZXggbV7zFY=,tag:++UfpdKu0jBUr+8Wq/h8cA==,type:str]
    SONARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:t+E7pVc/9Z4KUuEXkKKHXg==,iv:PdhhggQ1KLBkdgHB17YIU5Jziy4ajjwbJsXNmwa0H5w=,tag:5tVvg3xtYlDTEZnNgqjbHQ==,type:str]
    SONARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:xiuENEq5FdcjBqY=,iv:HGJNOeh+E0QQNUqZN8R3fevjea/Duy1Jakn97s2mob4=,tag:p/JUl7xETQu62FXFGaoZnA==,type:str]
    SONARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:oKj7UwG++lGqcQ==,iv:CHV1HINqOftRhC4R1ZIxT6Uptj4ywvTAbiwQc8UWsR4=,tag:BhcEpAVylVm/uO/ygOs80g==,type:str]
    #ENC[AES256_GCM,data:/6UItlW1fVtmMq3lLhs=,iv:muIET4Cs5povnC/M450D+XyENTz2x9rQYz7kOHGicTs=,tag:nxlIrnwy5e53qpooSVUmSQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:sW9pVGRtHijBYXOjg9Kl/GszqwCccA==,iv:3SI9i/1s6cLYX5D0d9hZXPjuqPuO0kzj46aRv4E/wXY=,tag:VMYVGJ+f5JAUYTa8IGwzDg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:huYUbKg2Xgw58lM6WMSi6CJHFaER+zSndhrM7uSoec0zK033tOXvSIPEl7WsnA==,iv:FQZOORnYV15c5qmqq8gtGakRzrAQl6Ammb+SoUNciSs=,tag:3oBDsjqRqKqokuguqsFRtA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:IrDmh3oC,iv:W8nH7MgUy7NX9cmIwNNOBiOlK1BLSFHdvYaIqckcanU=,tag:ifFfkCxvaCXBU+ui4G6dsg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:y4Ulix70DbUA2hgPeFQeIw==,iv:PruL3w6q5nboooCRIJxs85v/KLUk6myCmupIpwYKIho=,tag:7z0u5wr/hg4YtnzSQaFSZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT2c5aWFBUnR4S1V3K2pW
            SEE1NW9udG11TTR4Y1BPY0NIajVNVC8zVGdJCnF4bDlrQnNOUzRuUU5ldDhVUjdM
            SFM4MjEwVStvZGprRkRNQ1VjVHBJWjgKLS0tIGVzaVExdTAzc3I5WTR6M3FKOG9N
            Vy9MMlIzQWZHb0N4VCsrR0ZyYmVkWm8KqRELyc6QGtF0Mrx7xcI3VYNATjQC0BCg
            RX6rF7t1CXwKNJszyRqNnkahK0bbYEBSAg84ab76L2+lhM9amVZWzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T19:34:16Z"
    mac: ENC[AES256_GCM,data:24ltYqos4lptTB3oAlaoxzwLNK4kOJgt+9mxWpG3sYCa6oaeHWFyeLUHR7vQl+l89r5THMRWK6qv5NZdPWDKfbPXmqD+jSMeVN/EZoqXcmxSufuPPbJQaPMgcyi5Ht05oYqQu1UzOQoBbi8H5JlDbmCAnsd5b5oeoDIALM8JUg0=,iv:dgAMqz9v37MQtx3shB6CYuKXbGjna5yN/KGX+bX6FXE=,tag:bp3JfizovnydoksLxp981A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
