# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: nodered-secret
stringData:
    NODE_RED_CREDENTIAL_SECRET: ENC[AES256_GCM,data:0x4Bg6kG9s8Su7Iu1KB3S+k8R8f+wTSp,iv:CTze4+egQjXEUBTV2ErEc2XqjpZ7nus0/4OCdqXzDjE=,tag:cLD5V0WfXQ65kKKXbZZHgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTjFQSkgzL2dkQ2ZGbWZp
            YTlwS2hkUUthNVlIMzVZS2QrNHI2ZjlFQzFFCjBkNnl0V1ZpbG1yc0t2Z0JyVjRj
            OWpVeWM3YnBqUE55ek9aYklkSHZqQlUKLS0tIGE0cDZFUFRkcFhFTHhidFc0UUZl
            akxqQkEzWDUxWGVkZUxEa0VsbjFTYWMKgor+znx8JASSTJy6pM9IX4jwghjBVFKW
            UaDfDezqOTNNsgbVq7VsJ3QnyN5i6nfDYyzVkcPy8MY6n/a/Y/0FJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-23T11:39:29Z"
    mac: ENC[AES256_GCM,data:BYBb0PjUDFAw+ij8n1/+iitS+UuTgCjblak2lDS4egHlF3IMr1NC14uiKspKIhiOYF+/wENIn9u4VFm9VZzeBJGbHlyZBv8/uEvPva8j/xtxMy9TZMz+x+RoCsEwYjP2sgYDCAe55/Hh0vcFYYHzeEOQI17zZesrn5884ckunSE=,iv:IFp9wv7nMXdur2wHeHD9VI56jhywNXLs3A79iXnaVkw=,tag:oDUZ6BNQ8achNX80jliUxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
