---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
  reclaimPolicy: Delete
