# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: overseerr-secret
stringData:
    API_KEY: ENC[AES256_GCM,data:9XlGJI+UGefL1/M8NcOtgvmQ6a9vXsJuRYYVZgnOayJ6Wi54zS+FwmtJAZDTZb3Y90sXF13SrcfbcFDm261x4R4jixI=,iv:jV4uPk3i0ahCU6JC5klUz9E1oCcwWjRkliRu5jUel/k=,tag:rD93SEbJ7XfjQ0EON1/E1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdXp5bWcrb2tsUGlwSndh
            VzYvdWpTSGhPK04wbFRaZGxBT0VOQVZic1VzCnlickpaMTRWRDhTT0xOdUdPSnFK
            RytkM0V6cjlJbUdiYlhxdzIwWndJOGcKLS0tIDBacjhEQmprNkNXUG5MSmpJend3
            ZDRZR1RZdldPb1FHSkRuYnFBVyt5NW8Kd9d87TxmFenwZgLiEopcYnXXC967/cQh
            X0BM74H42SIkpmfuuzkib+Ty1AqMQr1Rn0KWAuCobU1rVkFDsPEIiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T16:31:27Z"
    mac: ENC[AES256_GCM,data:XywHKsI9se009ppAu55vX0iEh1QjwAXHIWIhjc2iYh/NwVaAOPOFdghI3X6w/uJfKSHORLqif7aDLuieWkQ+/0p8OPPoWMWhYJmZzhIyEqIcl0izskvZj22M933rUpKG8oM/liJqOGZR0+jiZI3CrHXkLfQsZZ9Y/Fgv0EBGIIE=,iv:V9wS2OTCRpyFrxMWZaqL1d7GFCGhBMxai79FjyPnDHk=,tag:S5RglbMj90ZwrXUQsRdHSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
