# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default
data:
    #ENC[AES256_GCM,data:coZbg5HJF++1ow==,iv:Le/Z+uQCjMnpDkrf/Zfqw34frG+IxhqRcs+bIDD4eAk=,tag:cCXEO25xjTXresSF/nsJ7A==,type:comment]
    username: ENC[AES256_GCM,data:ks4kiOmfnN0aSVr1,iv:YuZ/GrMoX27c3vMpQYERez3f9eAIfnasfjQL4d1ZDk8=,tag:/+bofSisKIkwmwMuR0Bubg==,type:str]
    password: ENC[AES256_GCM,data:ckx7cKw60PqY+KGJQ/pa6w==,iv:CeHCWYUsWxz+5KGL8kaGHe1+naQgVtwrgRB6ALxftb8=,tag:9Uc2L1QQkCUYpY8+T2aBIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVS9yb2FyMDRsUStvT0pn
            cXJrYzR3YnpWeURRZ1hDOEl0aGNCKzFmMG1FCnR1ZTBDL2FaY2E2RXhkWThna1B2
            MGltZDlXdUxaVTZaRUw3ZkVkcEcwZE0KLS0tIFBzL1RsakVobVB5SzRNdjFneDE5
            cnVSOHNvWTU3d214bVFZdjc0c3hsNDAKsRcL113Kw3TGCefrdq7mD1uX1q2EVVAg
            5sKlDYoIdgh+Ms80kWYLHl014h/k2WSg6baNzL7rMP4FysJtT98XHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T10:30:25Z"
    mac: ENC[AES256_GCM,data:R4TXvz4+25XwCj3WLigeojv/73OZafnJCCvvpMBE7Bg1m7t+gJTcKnIkry5jtRM7nKQF7j3r3zYzAvlfz/3lBaSgBxZWN9iT4luUOlp/ALrABdg2/mGhudXUOsyU939wTQi08QBC+eifasTASif4No+FPr/dk50JxagiEzUFHpg=,iv:q5ZkFf5TTGg5f5sfKLkceG27D0fH0UcQmW+437PTVWk=,tag:QhCitswgY46Yk4MN5PXNjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
