# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
data:
    #ENC[AES256_GCM,data:afiAyaySU62vHw==,iv:ULnlBOPkoaIFOkvsyGN/lH8G4Jwkd+xiKMrq5MW+bdc=,tag:O75YuqkmbGhLEvHyHfPdjQ==,type:comment]
    username: ENC[AES256_GCM,data:5EQPNijllwyZteQv,iv:0WPbxsWOVjwWwLYF986xEIMaaxMk2rhyFNPiIUw7he4=,tag:d63yBfZEFGSFiCAp1eTWsw==,type:str]
    password: ENC[AES256_GCM,data:eiqIWTiABaOVw4GqqQdz8g==,iv:ZLPVHaIeT3RCYabLM/H4avVDSzgtfVxSV28EClUVYxk=,tag:zXkNM1TUXqiqoU5dEQlOAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZHV4eGxQUFBqUGZLWmpR
            cEtRbUpoZjVjMDFIR2hGUU83a1REenFFZ2xvCk9lZk5yL2Fvc2pzSHdkc0xCK1lB
            SS9ZRVN4ZGRxTVdROFJtcnd0TC9mZkUKLS0tIGIvaTR2bzRCNjgyK0pvMFJZMFJX
            TUNiRjF4d0lZcHZGWW0rVEJxRUFuMUkKI0nS1iMRkv0pxkGlaIXyCSdIVgnhWmHi
            Rw4MVvm5ymO6nEHj5kEGeU1NS/5xpRdZjN9yI9w8fwjhhNhUgCh3Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T16:52:46Z"
    mac: ENC[AES256_GCM,data:e13QPut+yNysAA8OHp4M/WsERy+5QB/4wubG2iZevutmwN5pQfhBXbCZ4EkYpu7fX4ePm1pA+F2rWhrzNASgzPOJ9xuPlBvUyVOS+6OFlWpSllt9965G/6Z9PnzcPEwR4DSZbYo9XUVjsftveU7YFpZ92Td4LMrCj9ERf4H0HE0=,iv:p7YFm0G40jocnFWmSvhr+P0vBGmF56VtTTfsOe8zD20=,tag:vIHAjwkDKG35l0PDTNtolg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
