---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    template:
      engineVersion: v2
      data:
        PAPERLESS_ADMIN_USER: "{{ .username }}"
        PAPERLESS_ADMIN_MAIL: "{{ .email }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .password }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_DBHOST: &dbHost postgres-cluster-rw.database.svc.cluster.local
        PAPERLESS_DBUSER: &dbUser "{{ .PAPERLESS_POSTGRES_USER }}"
        PAPERLESS_DBPASS: &dbPass "{{ .PAPERLESS_POSTGRES_PASSWORD }}"
        PAPERLESS_DBNAME: paperless_main
        INIT_POSTGRES_DBNAME: paperless_main
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: paperless
