endpoints:
  - name: "${APP}"
    group: internal
    url: 1.1.1.1
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: "${GATUS_SUBDOMAIN:-${APP}}.exelent.click"
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: discord
