---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lubelogger
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lubelogger-secret
    template:
      engineVersion: v2
      data:
        # OIDC
        EnableAuth: "true"
        OpenIDConfig__ClientId: "{{ .OIDC_CLIENT_ID }}"
        OpenIDConfig__ClientSecret: "{{ .OIDC_CLIENT_SECRET }}"
        OpenIDConfig__TokenURL: "https://sso.exelent.click/application/o/token/"
        OpenIDConfig__AuthURL: "https://sso.exelent.click/application/o/authorize/"
        OpenIDConfig__RedirectURL: "https://lubelogger.exelent.click/Login/RemoteAuth"
        OpenIDConfig__LogOutURL: "https://sso.exelent.click/application/o/lubelogger/end-session/"
        OpenIDConfig__Name: Authentik
        OpenIDConfig__DisableRegularLogin: "true"
        OpenIDConfig__ValidateState: "true"
        # Email
        MailConfig__EmailServer: smtp.gmail.com
        MailConfig__Port: "587"
        MailConfig__EmailFrom: "{{ .EMAIL }}"
        MailConfig__Username: "{{ .EMAIL }}"
        MailConfig__Password: "{{ .EMAIL_PASSWORD }}"
        ## App Configuration
        POSTGRES_CONNECTION: 'Host={{ index . "pg_pgbouncer-host" }}:{{ .pg_port }};Username={{ .pg_user }};Password={{ .pg_password }};Database={{ .pg_dbname }}'
        UserNameHash: "{{ .ROOT_USERNAME_SHA256 }}"
        UserPasswordHash: "{{ .ROOT_PASSWORD_SHA256 }}"
  dataFrom:
    - extract:
        key: lubelogger-pguser-lubelogger
      sourceRef:
        storeRef:
          kind: SecretStore
          name: lubelogger-postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pg_$1"
    - extract:
        key: lubelogger
