---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lubelogger
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lubelogger-secret
    template:
      engineVersion: v2
      data:
        # init database
        INIT_POSTGRES_DBNAME: lubelogger
        INIT_POSTGRES_HOST: postgres-cluster-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .LUBELOGGER_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LUBELOGGER_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # OIDC
        EnableAuth: "true"
        OpenIDConfig__ClientId: "{{ .OIDC_CLIENT_ID }}"
        OpenIDConfig__ClientSecret: "{{ .OIDC_CLIENT_SECRET }}"
        OpenIDConfig__TokenURL: "https://sso.exelent.click/application/o/token/"
        OpenIDConfig__AuthURL: "https://sso.exelent.click/application/o/authorize/"
        OpenIDConfig__RedirectURL: "https://lubelogger.exelent.click/Login/RemoteAuth"
        OpenIDConfig__LogOutURL: "https://sso.exelent.click/application/o/lubelogger/end-session/"
        OpenIDConfig__Name: Authentik
        OpenIDConfig__DisableRegularLogin: "true"
        OpenIDConfig__ValidateState: "true"
        # Email
        MailConfig__EmailServer: smtp.gmail.com
        MailConfig__Port: "587"
        MailConfig__EmailFrom: "{{ .EMAIL }}"
        MailConfig__Username: "{{ .EMAIL }}"
        MailConfig__Password: "{{ .EMAIL_PASSWORD }}"
        ## App Configuration
        POSTGRES_CONNECTION: "Host=postgres-cluster-rw.database.svc.cluster.local:5432;Username={{ .LUBELOGGER_POSTGRES_USER }};Password={{ .LUBELOGGER_POSTGRES_PASSWORD }};Database=lubelogger;"
        UserNameHash: "{{ .ROOT_USERNAME_SHA256 }}"
        UserPasswordHash: "{{ .ROOT_PASSWORD_SHA256 }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: lubelogger
