---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mealie-secret
    template:
      engineVersion: v2
      data:
        # database
        DB_ENGINE: 'postgres'
        POSTGRES_SERVER: &dbHost postgres-cluster-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USER: &dbUser "{{ .MEALIE_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .MEALIE_POSTGRES_PASSWORD }}"
        POSTGRES_DB: &dbName mealie
        # init database
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # OIDC
        OIDC_AUTH_ENABLED: "True"
        OIDC_CONFIGURATION_URL: "https://sso.exelent.click/application/o/mealie/.well-known/openid-configuration"
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_ADMIN_GROUP: Infrastructure
        OIDC_AUTO_REDIRECT: "True"
        OIDC_PROVIDER_NAME: Authentik
        OIDC_REMEMBER_ME: "True"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: mealie
    - extract:
        key: Openai
      rewrite:
        - regexp:
            source: "(.*)"
            target: "OPENAI_$1"
