---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &app mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mealie-secret
    template:
      engineVersion: v2
      data:
        # database
        DB_ENGINE: 'postgres'
        POSTGRES_SERVER: mealie-pgbouncer.database.svc
        POSTGRES_PORT: "5432"
        POSTGRES_USER: *app
        POSTGRES_DB: *app
        POSTGRES_PASSWORD: "{{ .MEALIE_POSTGRES_PASSWORD }}"
        # OIDC
        OIDC_AUTH_ENABLED: "True"
        OIDC_CONFIGURATION_URL: "https://sso.exelent.click/application/o/mealie/.well-known/openid-configuration"
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_ADMIN_GROUP: Infrastructure
        OIDC_AUTO_REDIRECT: "True"
        OIDC_PROVIDER_NAME: Authentik
        OIDC_REMEMBER_ME: "True"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
  dataFrom:
    - extract:
        key: mealie
    - extract:
        key: Openai
      rewrite:
        - regexp:
            source: "(.*)"
            target: "OPENAI_$1"
