---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./clusterparser-logfmt.yaml
  - ./clusterfilter-logfmt.yaml
  - ./clusterfilter-level-map.yaml
  - ./clusteroutput-victorialogs.yaml
