---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communitcate:
        - Discord:
            - icon: discord.png
              href: https://discord.com/app
    - Git:
        - onedr0p:
            - icon: github.png
              href: https://github.com/onedr0p/home-ops
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: https://kubesearch.dev
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    gateway: true
    ingress: false
    traefik: false
  services.yaml: |
    - Home Apps:
        - Spruthub:
            href: https://sprut.exelent.click
            icon: https://spruthub.ru/favicon.ico
            description: Zigbee hub and Homekit integration
    - Monitoring & Observability:
        - Cloudflared:
            href: https://dash.cloudflare.com
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel
            widget:
              type: cloudflared
              accountid: "{{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}"
              tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}"
              key: "{{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}"
    - Infrastructure:
        - Unifi:
            href: https://unifi.exelent.click
            icon: unifi-controller.png
            description: Home Network Management
            widget:
              type: unifi
              url: https://192.168.20.1
              username: "{{HOMEPAGE_VAR_UNIFI_USERNAME}}"
              password: "{{HOMEPAGE_VAR_UNIFI_PASSWORD}}"
        - Synology:
            href: https://nas.exelent.click
            icon: synology.png
            description: Synology nas disk station
            widget:
              type: diskstation
              url: http://192.168.20.5:5000
              username: "{{HOMEPAGE_VAR_SYNOLOGY_USERNAME}}"
              password: "{{HOMEPAGE_VAR_SYNOLOGY_PASSWORD}}"
        - Proxmox:
            href: https://proxmox.exelent.click
            icon: proxmox.png
            description: Virtual Environment
            widget:
              type: proxmox
              url: https://192.168.0.41:8006
              username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
              password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"
              node: proxmox1
        - Minio:
            href: https://minio.exelent.click
            icon: minio.png
            description: S3 compatible object storage
  settings.yaml: |
    title: Pohulanka home
    theme: dark
    color: slate
    headerStyle: boxedWidgets
    layout:
        Home Apps:
          icon: mdi-home-assistant
          style: row
          columns: 2
        Media & Downloading:
          icon: mdi-movie
          style: row
          columns: 4
        Monitoring & Observability:
          icon: mdi-chart-line
          style: row
          columns: 3
        Infrastructure:
          icon: mdi-server
          style: row
          columns: 3
    providers:
      longhorn:
        url: http://longhorn-frontend.storage.svc.cluster.local
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - greeting:
        text_size: xl
        text: "Welcome!"
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true
