---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_TAG }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLUSTER_CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_HOMEPAGE_TUNNEL_SECRET }}"
        HOMEPAGE_VAR_SYNOLOGY_USERNAME: "{{ .HOMEPAGE_SYNOLOGY_USERNAME }}"
        HOMEPAGE_VAR_SYNOLOGY_PASSWORD: "{{ .HOMEPAGE_SYNOLOGY_PASSWORD }}"
        HOMEPAGE_VAR_PROXMOX_USERNAME: "{{ .HOMEPAGE_PROXMOX_USERNAME }}"
        HOMEPAGE_VAR_PROXMOX_PASSWORD: "{{ .HOMEPAGE_PROXMOX_PASSWORD }}"
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .UNIFI_HOMEPAGE_USER }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .UNIFI_HOMEPAGE_PASSWORD }}"
        ## Default
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: "{{ .homepage_qbittorrent_username }}"
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .homepage_qbittorrent_password }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        HOMEPAGE_VAR_OVERSEERR_TOKEN: "{{ .OVERSEERR_TOKEN }}"
        HOMEPAGE_VAR_PAPERLESS_TOKEN: "{{ .PAPERLESS_TOKEN }}"
        HOMEPAGE_VAR_TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
        HOMEPAGE_VAR_AUDIOBOOKSHELF_TOKEN: "{{ .AUDIOBOOKSHELF_HOMEPAGE_TOKEN }}"
        HOMEPAGE_VAR_MEALIE_TOKEN: "{{ .MEALIE_HOMEPAGE_TOKEN }}"
        HOMEPAGE_VAR_LUBELOGGER_USERNAME: "{{ .LUBELOGGER_username }}"
        HOMEPAGE_VAR_LUBELOGGER_PASSWORD: "{{ .LUBELOGGER_password }}"
        ## Observability
        HOMEPAGE_VAR_PORTAINER_TOKEN: "{{ .HOMEPAGE_PORTAINER_TOKEN }}"
        HOMEPAGE_VAR_GRAFANA_USER: "{{ .grafana_username }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .grafana_password }}"
        ## Security
        HOMEPAGE_VAR_AUTHENTIK_TOKEN: "{{ .AUTHENTIK_TOKEN }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: cloudflare
    - extract:
        key: synology
    - extract:
        key: proxmox
    - extract:
        key: qbittorrent
      rewrite:
        - regexp:
            source: "(.*)"
            target: "homepage_qbittorrent_$1"
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: prowlarr
    - extract:
        key: plex
    - extract:
        key: tautulli
      rewrite:
        - regexp:
            source: "(.*)"
            target: "TAUTULLI_$1"
    - extract:
        key: overseerr
    - extract:
        key: portainer
    - extract:
        key: paperless
    - extract:
        key: grafana
      rewrite:
        - regexp:
            source: "(.*)"
            target: "grafana_$1"
    - extract:
        key: audiobookshelf
      rewrite:
        - regexp:
            source: "(.*)"
            target: "AUDIOBOOKSHELF_$1"
    - extract:
        key: unifi
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "UNIFI_$1"
    - extract:
        key: mealie
    - extract:
        key: lubelogger
      rewrite:
        - regexp:
            source: "(.*)"
            target: "LUBELOGGER_$1"
