---
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "1edce6bd4d53289269e8fd922b23c411"
  HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "69357070-5a68-4794-87a6-d20dc84e1d82"
  HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "nzpav6bifqblfuji2mdyn_specw8g5jmzpzbvxdf"
