apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:Xm9PmwPYOlTNCEtkO9GNr6dlSG7ajo0E4mrjILTjDRo=,iv:g/VfAECpLO72FXfSf0ZQ2odr+TKbeYUMllZU0A5Oc/Y=,tag:7lST6CQXyHWIK+xny7Fw2Q==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:BHyOkMBdqGIPMCb9T29NBQZ7xdL+/ucrD7QqIqVyqedBUPw5,iv:U050WvLKeUVA95fskNE3irhL9LdU3f1fxP2B4wc74Fw=,tag:OOaSrJs0KzMmFJ10Vfz5aw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:FuPjfAYvLiDjLAYuLVkRfHNgl/chUrhXHeiR95h9L2o6XPF8T5W/NA==,iv:uT1IJk//BG7rYAlUqBhVbdt1VstoktbHj3U/36P8ru8=,tag:eDtb5OYsjfrSahgIGFkCHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYm54dXVpU0oxWGNhQUhk
            WGYydjI2QW93cng4Nk5LaFV5TnNMQVhmVmxvCkY3dFBPR0RuVVlCNEE0WjljQnRL
            eVRWejIxL2lMMGlzWmxEQTJLT2ZWaXMKLS0tIGZUR1Q5UGlBejdMTHo0MC9xWjdX
            Q1NTTVZKN08xZThlT3BLYmxZamhUQzAK/YWUcZnSOotNutAgtL73Q7qmAvDBDyjW
            PVyaC8B5IEWUdg+jacQiGYH4AGvLgKgy2NoNPi5QwgHQypDqYWZCaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-02T15:08:58Z"
    mac: ENC[AES256_GCM,data:4yRja3ffLYuJTrgIC+DB9ZZbDbJHwr2IPxJufCBD8MeKaNq1XYFRFHRFSLrKJnG43NKWq6KZU56jS6CBiWlQFCfr7KlQfGtiAvDsjt4vltqs45VGJ63pManPDyWjGlqaudyJWAA1WwglP2qNjnYrqW9sxnn/MQUwT6XxQYBr5ek=,iv:Re53aWdArzEHfuCPPUTAZY0JS5ge84WG58kciYHAFr4=,tag:/NbPmkopv5r5t2JhpvmdCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
