apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:bm+WVXwBryy4CI00V5Bq0x6Tmf3p9UHWBHITjTbLDF4=,iv:VLYgpMtLEyJp2LRIKq9Hj6J4V57oHsiVxq6Ar3kCRH4=,tag:JOoFn+S+++L8Sc8EMwfTRQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:qQV/UzWs48MKRCaASbpBHvFb/zuUHYlXGfhXBmu1ns3JfKHG,iv:GQPmvT72PD+P+2MgqX5GRtiURJPeJC1RUjMP310DyB4=,tag:itu+wvnTxoTO0KsxNj/+yw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:B4Clf7Qvhuo2oH+l6LS+9YBwmyc4eBEFawuZ7NWa5rDZ3VmgtCaztQ==,iv:PU/owHccMAjGiee4K/pFOWAgElIXPoIKxb/J1bPyxVg=,tag:aO8wQ66MMV48uFLYKGUrYA==,type:str]
    HOMEPAGE_VAR_SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:okP1k7IB2PmezADu,iv:9Y8ZqC3KZuwvY2c08ezMWYUtCEn3EMD19ijG9KKnSes=,tag:6CUD53VeyWee9pl5vbp5VQ==,type:str]
    HOMEPAGE_VAR_SYNOLOGY_USERNAME: ENC[AES256_GCM,data:yGTnz6UW3XTzb/nK+O8WZQ==,iv:PvPF5eJ0P67FH4wK93CIY/gnMG98RLB3a2314+EB5kQ=,tag:Xim1izzEjJaGVxx3er5cNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbSsxVmg1QUJFN0NCVUtv
            YXpMRW4wc29tWk9TMUp5Y2FhMlVLNHhRTjFNCnVqM0VjaStTQmErdkJhK1RReHJV
            REs1cm8yRkJIQ251TTU0MTVmTUxsdEkKLS0tIGlWdmI2V3d4K3czYUxBbnZDK280
            a3hjaEo5eHVYOW03Q0dQVU94VFlMZVEKVkzIlg+pQGiOwLMh41+Ui31o7U8yyCBp
            bFYrAxSHmnPoJbTsLNw82m2fWdJ93mphr4nugnJ0EzO7I5Fjd7+rEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T19:44:51Z"
    mac: ENC[AES256_GCM,data:l6ajl5FOmEgEOYlE2K4P1SGizjVZtiAwsf0urvV5V55qAiq55s3nWix0bZKU187i0/UOid72SfzW18fK+zF/iExxmRWqPOhQGCQte8jZ/QSMPeV3+ApqzFFsBMxpjlIwC+T+IXE7KZBurUU4M8YTrAVul9GASKCAA68xacZO2FU=,iv:z0ri4vC+fTpMBiGAITwXuJV3WbXb2HexpGouHZsEx9g=,tag:K5h4UEqpa/SndkDMeQ07aA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
