---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: APP_NAME
spec:
  chartRef:
    kind: OCIRepository
    name: APP_NAME
  interval: 1h
  values:
    controllers:
      APP_NAME:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: APP_IMAGE
              tag: VERSION
            env:
              TZ: "Europe/Warsaw"
            # Paste if have secret with envs
            envFrom:
              - secretRef:
                  name: APP_NAME-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ "ALL" ] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        # Add if it needs to have local network ip
        annotations:
          lbipam.cilium.io/ips: 192.168.20.65
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: [ "{{ .Release.Name }}.exelent.click" ]
        parentRefs:
          - name: envoy-internal
            namespace: network
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: APP_NAME.png
          gethomepage.dev/name: APP_NAME
          gethomepage.dev/group: "APP_GROUP"
          gethomepage.dev/description: APP_DESCRIPTION
          gethomepage.dev/weight: "7"
    persistence:
      server:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /path/to/the/data
      saves:
        type: nfs
        server: "192.168.20.5"
        path: "/volume1/kubernetes/path"
        globalMounts:
          - path: /to/the/nfs/data
