---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app APP_NAME
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      # Retries is the number of retries that should be attempted on failures before bailing. Remediation, using an uninstall, is performed between each attempt.
      retries: -1
  upgrade:
    # CleanupOnFail allows deletion of new resources created during the Helm rollback action when it fails
    cleanupOnFail: true
    remediation:
      retries: 3
  # Generally storage dependencies goes here
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
  values:
    controllers:
      APP_NAME:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: APP_IMAGE
              tag: VERSION
            env:
              TZ: "Europe/Warsaw"
            # Paste if have secret with envs
            envFrom:
              - secretRef:
                  name: APP_NAME-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ "ALL" ] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [ 10000 ]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        # Add if it needs to have local network ip
        annotations:
          lbipam.cilium.io/ips: 192.168.20.65, ::ffff:192.168.20.65
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: [ "{{ .Release.Name }}.exelent.click" ]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      server:
        existingClaim: *app
        globalMounts:
          - path: /path/to/the/data
      saves:
        type: nfs
        server: "192.168.20.5"
        path: "/volume1/kubernetes/path"
        globalMounts:
          - path: /to/the/nfs/data
