---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
data:
  IMMICH_CONFIG_FILE: "/config/immich.config.json"
  REDIS_HOSTNAME: "dragonfly-immich.database.svc.cluster.local"
  REDIS_DBINDEX: "0"
  DB_HOSTNAME: "postgres-immich-rw.database.svc"
  DB_USERNAME: "immich"
  DB_DATABASE_NAME: "immich"
