---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbtools-emonoda
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbtools-emonoda-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          core:
              client: qbittorrent2
              torrents_dir: /data/torrents/.torrents/completed
          client:
              url: http://qbittorrent.default.svc.cluster.local:8080
              user: {{ .qbittorrent_username }}
              passwd: {{ .qbittorrent_password }}
          trackers:
              rutracker.org:
                  user: {{ .rutracker_username }}
                  passwd: {{ .rutracker_password }}
  dataFrom:
    - extract:
        key: rutracker
      rewrite:
        - regexp:
            source: "(.*)"
            target: "rutracker_$1"
    - extract:
        key: qbittorrent
      rewrite:
        - regexp:
            source: "(.*)"
            target: "qbittorrent_$1"
