---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent-tools-emonoda
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: default
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          # run it after qbit-helper
          schedule: "10 * * * *"
          timeZone: "Europe/Warsaw"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          main:
            image:
              repository: ghcr.io/mglants/emonoda
              tag: 2.1.37
            command:
              - emupdate
            args:
              - --config
              - /app/config.yaml
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 256M
        pod:
          restartPolicy: OnFailure
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values: [ "qbittorrent" ]
                  topologyKey: kubernetes.io/hostname
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      qbittorrent:
        existingClaim: qbittorrent
        globalMounts:
          - path: /config
      config-file:
        type: secret
        name: qbtools-emonoda-secret
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
            readOnly: true
      downloads:
        type: nfs
        server: "192.168.20.5"
        path: "/volume1/kubernetes"
        globalMounts:
          - path: /data
