apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:dO7E0qDAA8Vn2Q8Chm9ApcVZS6vO8EJ8c0WAbiWOO+2iFbI+Ih5PGw==,iv:+v4L8dxExjjPs0VYG02Mb9IllSX8ZS3ZA3YBLQaGIXQ=,tag:/+ge2Mv7x/Xj/kdoWEZlww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k5xl02aujw4rsgghnnd0sdymmwd095w5nqgjvf76warwrdc0uqpqsm2x8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWE9GdXJaVXpzM1h3eVB4
            NzhkZXhEcG02YzhTTmgrMmhvTHRjci9DUXdzCkVod2Q5YVJYY0tZcWdxcU9uZm1U
            dkswTVpQMEc5a0NvcFdkY0NTVzk2aEUKLS0tIG1tazFLWWxMa2IvbEZwUlphTmt5
            Y2NjNWozR3hhdzdHR3h0RFl1SS9nTm8K9uQOyVqtUb66P4LiQ2hNC+fuio/ydb4t
            vCF7JsEHN7opgXPXmzIH643nzIO/jNeUc1XNDlMAlaiTqgLFFisHTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-17T21:45:25Z"
    mac: ENC[AES256_GCM,data:YcvkU7V4HBBJWhkgB8KO1Sm8/jLsff8NFCtcmEk+mOwM8Bd+XK2QPV4FNzHCEqOVgh7m9Bmf9mzYUdXC8wg/2VioWToaI2i5Z0bmAwaKrUWzl14+3e80dh1p418STLGx/B8o1ywQM1yOCMaM0/z5Q5gVbxxY8OLSToKIhpdmn48=,iv:JyTD8nT1Ki4ZuutdWlk2gcKARlhswcgz7eHc9PlWtIk=,tag:DJzgjGC3LYCIuLHavWoc5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
