---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komga
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: komga-secret
    template:
      type: Opaque
      data:
        application.yml: |
          spring:
            security:
              oauth2:
                client:
                  registration:
                    authentik:
                      provider: authentik
                      client-id: {{ .OIDC_CLIENT_ID }}
                      client-secret: {{ .OIDC_CLIENT_SECRET }}
                      client-name: SSO
                      scope: openid,profile,email
                      authorization-grant-type: authorization_code
                      # the placeholders in {} will be replaced automatically, you don't need to change this line
                      redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
                  provider:
                    authentik:
                      user-name-attribute: preferred_username
                      issuer-uri: https://sso.exelent.click/application/o/komga/
  dataFrom:
    - extract:
        key: komga
