---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Lychee"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".github/workflows/lychee.yaml"]
  schedule:
    - cron: "0 0 * * *"

env:
  LYCHEE_OUTPUT: lychee/out.md
  WORKFLOW_ISSUE_TITLE: "Link Checker Dashboard 🔗"

jobs:
  lychee:
    name: Lychee
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Scan for broken links
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          token:  "${{ steps.app-token.outputs.token }}"
          args: --verbose --no-progress --exclude-mail './**/*.md'
          format: markdown
          output: "${{ env.LYCHEE_OUTPUT }}"
          debug: true

      - name: Find Link Checker Issue
        id: find-issue
        shell: bash
        env:
          GH_TOKEN: "${{ steps.app-token.outputs.token }}"
        run: |
          issue_number=$( \
              gh issue list \
                  --search "in:title ${{ env.WORKFLOW_ISSUE_TITLE }}" \
                  --state open \
                  --json number \
                  | jq --raw-output '.[0].number' \
          )
          echo "issue-number=${issue_number}" >> $GITHUB_OUTPUT
          echo "${issue_number}"

      - name: Create or Update Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          token:  "${{ steps.app-token.outputs.token }}"
          title: "${{ env.WORKFLOW_ISSUE_TITLE }}"
          issue-number: "${{ steps.find-issue.outputs.issue-number || '' }}"
          content-filepath: "${{ env.LYCHEE_OUTPUT }}"
