---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/common
resources:
  - ./cloudflare-tunnel/ks.yaml
  - ./cloudflare-dns/ks.yaml
  - ./echo/ks.yaml
  - ./unifi-dns/ks.yaml
  - ./k8s-gateway/ks.yaml
#  - ./external-services/ks.yaml TODO redeploy
  - ./playit/ks.yaml
